name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        vim_version:
          - head
          - v9.1.0000
          - v9.0.0000
          - v8.2.0000
          - v8.1.0001
          - v8.0.0002
          - v7.4
        platform:
          - Linux
          - macOS
          - Windows
        include:
          - platform: Linux
            os: ubuntu-latest
            download: never
          - platform: macOS
            os: macos-latest
            download: never
          - platform: Windows
            os: windows-latest
            download: always
      fail-fast: false
    name: Vim ${{ matrix.vim_version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Checkout themis.vim
        uses: actions/checkout@v4
        with:
          repository: thinca/vim-themis
          persist-credentials: false
          path: vim-themis
      - name: Disable NLS on macOS
        if: matrix.platform == 'macOS'
        run: rm -f $(which msgfmt)
      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@v2
        with:
          vim_version: ${{ matrix.vim_version }}
          download: ${{ matrix.download }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Primula
        run: |
          python -m pip install -U pip
          python -m pip install -U primula
      - name: Test
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          primula run ./vim-themis/bin/themis --reporter spec
          primula report -m
      - name: Generate XML coverage report
        run: primula xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: ${{ matrix.platform }}
          plugins: noop
